### PR TITLE
Fix begins with / ends with markers

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Comment by timgws** [comment]
hahahaha, whoops.

\*_slowly backs away_*

**Comment by timgws** [comment]
Thanks for this PR, @morrislaptop.

I have written a test for this: https://github.com/timgws/QueryBuilderParser/commit/035a3f34b2c4fb6a4a98d7752d0c88ec72c6a663

**Comment by morrislaptop** [comment]
Haha no worries ;) FYI I'm using this with @jenssegers mongodb builder and it's all working great so far!

**Comment by timgws** [comment]
Awesome!



I will add a note in the README :)




---- On Tue, 23 Feb 2016 20:33:54 +1100 Craig Morris &lt;notifications@github.com&gt;wrote ---- 




Haha no worries ;) FYI I'm using this with @jenssegersmongodb builder and it's all working great so far!

**Pull request merged**
